### ISSUE TITLE
hexo部署在gitPage

### ISSUE THREAD

**Issue by zjy7** [zjy7/blog#24]
cnpm i hexo-cli -g
hexo init blog
cd blog
cnpm i
hexo server   //在本地部署

cnpm install hexo-deployer-git --save

hexo d -g    //部署在gitPage

vim _config.yml
```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:bale77/bale77.github.io.git
  branch: master
  message: "{{ now ('YYYY-MM-DD HH:mm:ss') }}"
```
